tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'
vscode:
  extensions:
    - netanelgilad.opah

image:
  file: ./.gitpod/Dockerfile