# action.yml
name: "Opah"
description: "Run an opah function"
inputs:
  repo-token:
    description: "The repository token"
    required: true
runs:
  using: "docker"
  image: netanelgilad/opah
  args:
    - ./.github/actions.ts
    - default
    - '"${{ inputs.repo-token }}"'
