# action.yml
name: "Opah"
description: "Run an opah function"
inputs:
  npm-access-token:
    description: "Npm access token"
    required: true
runs:
  using: "docker"
  image: netanelgilad/opah
  args:
    - ./.github/actions.ts
    - default
    - '"${{ inputs.npm-access-token }}"'
