on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Push docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./.github/actions
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
